### PR TITLE
various fixes

### PR DESCRIPTION
**Pull request by BaneusCatrix**
the following things where  fixed or changed:

- added packages rust and cargo to build image, fixing error "no rust compiler found"
- changed version tag for alpine image from 3.10 to 3.12 because the rust compiler in 3.10 is to old to build the ansible cryptography package

After these changes I got a successful build run with minor warnings.

### CODE REVIEW

**Comment by scaleoutsean** [comment]
@DustinBragg can you review this and accept if OK?
We could also update Grafana for #11 and potentially recheck if documentation needs clarifications or updates.

**Comment by ljdelight** [comment]
Hi @BaneusCatrix, I appreciate the patch! We have a new contribution workflow, please read [CONTRIBUTING.md](https://github.com/NetApp/eseries-perf-analyzer/blob/master/CONTRIBUTING.md) and fill out the CLA mentioned in step 6, then we'll get this reviewed / merged in. Thanks

**Comment by scaleoutsean** [comment]
@BaneusCatrix do you have time to fill the CLA so that this patch can be accepted?

**Comment by BaneusCatrix** [comment]
@scaleoutsean Now jet, I'm going to tomorrow. Sorry for the delay, I have to consult my legal department.

**Comment by gmarks-ntap** [comment]
The recent updates for version 3.0 of the performance analyzer should address the issues addressed by this PR. I'm going to close the PR. Please let us know if the build image is not fixed for you with the 3.0 version.

**Pull request closed without merging**
